#!/bin/bash

# Generated by LLM for Ubuntu, not tested.

# correspond to Windows echo %userprofile%
echo "user dir: $HOME"

# Ubuntu default terminal: gnome-terminal
# Size 200 Col × 10 Line, pos: x=0 y=750
# exe python summon.py
gnome-terminal --geometry=200x10+0+750 -- bash -c "python3 summon.py; exec bash"
